version: "3.0"

services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "7002:7002"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: articles-service

volumes:
  postgres:
